SELECT 
      [createdon]
      ,[modifiedon]
      ,[createdbyname]
      ,[modifiedbyname]
      ,[owneridname]
      ,[statecode]
      ,[statecodename]
      ,[statuscode]
      ,[statuscodename]
      ,[cr301_title]
      ,[cr301_code]
      ,[cr301_is_deleted]
      ,[cr301_nphiescode]
      ,[cr301_nphiesdescription]
      ,[cr301_price]
      ,[cr301_productcategory]
      ,[cr301_service]
      ,[cr301_servicear]
      ,[cr301_servicekey]
      ,[cr301_sharepointid]
      ,[cr301_specialty]
      ,[cr301_status]
      ,[cr301_businessunitname]
      ,[cr301_servicecategoryname]
      ,[cr301_specialtyname]
      ,[servhub_priced]
      ,[cr18c_buname]
  FROM [dbo].[cr301_ksaservicedataset]
  where cr301_status = 'Active'
  and cr18c_buname in ('HJH','AHJ','LCH','MKR','AKW','ALW','SNB','AFW','ADC')
  order by createdon desc